name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Shopify CLI
      run: npm install -g @shopify/cli @shopify/theme

    - name: Authenticate and Deploy Theme
      env:
        SHOPIFY_STORE_URL: ${{ secrets.SHOPIFY_STORE_URL }}
        SHOPIFY_ADMIN_API_KEY: ${{ secrets.SHOPIFY_ADMIN_API_KEY }}
        SHOPIFY_ADMIN_API_PASSWORD: ${{ secrets.SHOPIFY_ADMIN_API_PASSWORD }}
      run: |
        # Create a configuration file for Shopify CLI
        mkdir -p ~/.config/shopify
        echo "store: $SHOPIFY_STORE_URL" > ~/.config/shopify/config
        echo "password: $SHOPIFY_ADMIN_API_PASSWORD" >> ~/.config/shopify/config
        # Deploy the theme
        shopify theme push --store $SHOPIFY_STORE_URL --password $SHOPIFY_ADMIN_API_PASSWORD --theme ${{ secrets.SHOPIFY_THEME_ID }}
