name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Theme Kit
      run: |
        curl -s https://shopify.github.io/themekit/scripts/install | sudo bash || true
        wget https://github.com/Shopify/themekit/releases/latest/download/theme_linux_amd64 -O theme
        chmod +x theme
        sudo mv theme /usr/local/bin/theme

    - name: Deploy to Shopify
      env:
        SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_PASSWORD }}
        SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE }}
        SHOPIFY_THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
      run: |
        theme deploy --password=$SHOPIFY_PASSWORD --store=$SHOPIFY_STORE --themeid=$SHOPIFY_THEME_ID
