name: Deploy Shopify Theme

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Theme Kit
        run: npm install @shopify/themekit

      - name: Print Environment Variables
        run: |
          echo "Shopify Store URL: $SHOPIFY_STORE"
          echo "Shopify Theme ID: $THEME_ID"

      - name: Deploy to Shopify
        env:
          SHOPIFY_PASSWORD: ${{ secrets.SHOPIFY_API_PASSWORD }}
          SHOPIFY_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
          THEME_ID: ${{ secrets.SHOPIFY_THEME_ID }}
        run: |
          echo "Deploying theme to Shopify store: $SHOPIFY_STORE"
          theme deploy --password=$SHOPIFY_PASSWORD --store=$SHOPIFY_STORE --themeid=$THEME_ID --dir=.
          echo "Deployment completed"
